### ISSUE TITLE
Improve SEO

### ISSUE THREAD

**Issue by dandv** [webix-hub/tracker#149]
Webix looks like a very powerful UI widget library, but apparently very few people know about it:

* http://stackoverflow.com/questions/200284/what-are-alternatives-to-extjs only mentions Webix because I maintain that community answer
* [Nobody on Quora](https://www.quora.com/What-advanced-front-end-widget-libraries-are-out-there) knew about Webix (I've Asked to Answer the maximum amount of users I could)
* Nobody on [Meteor-talk](https://groups.google.com/forum/#!topic/meteor-talk/sX35EByIRNg) knew about it ([Meteor](http://github.com/meteor/meteor) itself has ~21,000 GitHub stars).

https://github.com/webix-hub should have a description and a logo.

Each repo should have a description (which is searchable from GitHib) and a URL as well.

Etc.

**Comment by mkozhukh** [comment]
Thanks for suggestion

**Comment by dandv** [comment]
@mkozhukh: Another suggestion: please add relevant tags: JavaScript, widgets etc. "webix" itself isn't helpful because someone who doesn't know about "webix" but searches for "JavaScript widgets library" won't be helped by the "webix" tag.

![image](https://user-images.githubusercontent.com/33569/42719719-67a9889e-86cf-11e8-82ad-9d04a2a7f6c9.png)
