### ISSUE TITLE
Take demos out of iframe

### ISSUE THREAD

**Issue by dandv** [webix-hub/tracker#151]
All [Webix demos](http://webix.com/demo/tree/basic/) are presented in a tiny iframe, with a laptop image background. This creates a negative impression (is this library responsive? how would controls resize? do I need an iframe or styles will leak etc.)

[Kendo UI does demos well](http://demos.telerik.com/kendo-ui/grid/editing-custom-validation).

**Comment by HannaBabrouskaya** [comment]
Webix demos were taken out of iframe.
