### ISSUE TITLE
Typos in quick start

### ISSUE THREAD

**Issue by dandv** [webix-hub/tracker#159]
http://webix.com/quick-start/#!/3
> An empty row or column has to properties and no component inside -> "no properties"

http://webix.com/quick-start/#!/4
> All webix components and controls feature view property where you specify component/control name to be created -> "All Webix components and controls have a view property that specified the name of the component/control to be created"

> Note that one you've set a toolbar -> "Note that once you've defined a toolbar"

http://webix.com/quick-start/#!/5

> Form houses various controls to get data from users: -> "Forms contain various controls to get data from users"

> They are arranged in rows/elements and cols, with resembles layout and toolbar very much. -> "The controls are arranged in rows/elements and cols, very much like layouts and toolbars."

http://webix.com/quick-start/#!/6

> Setting List -> "Setting up a List", or "Using Lists"

> **template** to define data values to show for each of its items. Template values must be in hash-signs -> "**template** to define how to show the values for each item. Field placeholders ([template tags](https://github.com/meteor/meteor/blob/devel/packages/spacebars/README.md)) are specified between # signs, e.g. `#title#`"

> In case JSON, you can do without direct datatype specification. -> "**datatype** defaults to `JSON`", or just omit that sentence, since it's already mentioned in the previous sentence, "Webix supports JSON (default)"

> Try to disable selection (either by setting false or by deleting this property at all), apply code and click any item; -> "Try to disable selection (either by setting the property to false, or by deleting it all together), Apply the changes, and click any item;"

> Try changing some values in the dataset and apply code. -> "Try changing some values in the dataset and apply the changes."

**Comment by Zwillinge** [comment]
Fixed.
