### ISSUE TITLE
TreeTable adjustColumn does not account width correctly for header. (Chrome only)

### ISSUE THREAD

**Issue by reynardmc22** [webix-hub/tracker#16]
This is a fairly small isolated issue, that I've only seen in Chrome (IE and iOS are fine in my testing).  The below code will cause the issue where the 2nd column's name word wraps and doesn't show.  Changing spaces to %nbsp; seems to fix the issue and it only seems to happen on the 2nd column.

```
    var bookmarks = new webix.DataCollection({
        data: [
                { "id":"1", "value":"100%", "open":true, "data":[
                    { "id":"1.1", "value":"20%", "chapter":"alpha"},
                    { "id":"1.2", "value":"10%", "chapter":"beta", "open":true, "data":[
                        { "id":"1.2.1", "value":"15%", "chapter":"beta-twin"},
                        { "id":"1.2.2", "value":"20%", "chapter":"beta-twin"},
                    ]},
                    { "id":"1.3", "value":"10%", "chapter":"gamma" }
                ]},
                { "id":"2", "value":"50%", "data":[
                    { "id":"2.1", "value":"25%", "chapter":"alpha" },
                    { "id":"2.2", "value":"10%", "chapter":"beta" }
                ]}
            ]
    });


        grid = new webix.ui({
            container:"testA",
            view:"treetable",
            columns:[
                { id:"id",  header:"ID value", template:"{common.treetable()} #id#"},
                { id:"value",   header:"% Scripts"},
                { id:"value",   header:"% Scripts"},
                { id:"value",   header:"% Scripts"}
            ],
            autoheight:true,
            autowidth:true,
            data:bookmarks.serialize()
        });     

        grid.eachColumn(function(col) {
                grid.adjustColumn(col, true);
        });
        grid.refreshColumns();
```

**Comment by reynardmc22** [comment]
Can we reopen this now for IE in version 2.1.1.   Using the air.css not sure if i happens in the default.  I just added 12 pixels to the header and it seems to work fine but probably not a great fix.

**Comment by mkozhukh** [comment]
Check the next snippet, it uses 2.1 version and air skin - it looks correctly for me.
If you have the problem in your app - try to place webix.ui code inside of webix.ready ( so it will start only after page loading ) 

http://webix.com/snippet/767076f1

**Comment by dandv** [comment]
@mkozhukh: the link in your first reply, http://docs.webixui.com/builds/, looks interesting. Can you fix it to indicate the current place to download Webix builds?
