### ISSUE TITLE
Publicize the membership of Webix devs to the organization

### ISSUE THREAD

**Issue by dandv** [webix-hub/tracker#176]
One way to increase the credibility of Webix would be to make public the membership of Webix devs to the webix-hub organization. Right now, the People section of https://github.com/webix-hub reads

> This organization has no public members. 

This creates the impression of an abandoned or early stage project with a very small team.

### How to fix

Webix devs who want to publicly display the Webix in their profile can go to https://github.com/orgs/webix-hub/people, and find your name in the list. Click the "Private" drop-down option and change it to Public.

CC @mkozhukh, @Maria-Staskova, @vikator, @Zwillinge, @dmitry-radyno, @Nadezhda13  etc.

**Comment by mkozhukh** [comment]
Thanks for suggestion
