### ISSUE TITLE
What is WebixConnector?

### ISSUE THREAD

**Issue by dandv** [webix-hub/tracker#180]
At http://docs.webix.com/datatree__loading_data.html, the link to WebixConnector is broken. WebixConnector is also mentioned at http://docs.webix.com/datatable__loading_data.html but I couldn't find any docs.webix.com page about it.

**Comment by mkozhukh** [comment]
Connectors is just one of possible backends for the Webix components. 
It is a data abstraction layer which simplify loading and storing the data. 

http://docs.dhtmlx.com/connector__php__index.html

Link is fixed by the way

**Comment by dandv** [comment]
Hi @mkozhukh, thanks for going through the tickets. I see the link to WebixConnector is still http://docs.webix.com/doku.php?id=Webixconnector:toc at http://docs.webix.com/datatree__loading_data.html. Maybe I need to wait for the next docs site update?
