### ISSUE TITLE
How does dynamic data loading for trees work?

### ISSUE THREAD

**Issue by dandv** [webix-hub/tracker#181]
I've read the [guide on loading big datasets for trees](http://docs.webix.com/datatree__loading_data.html) but it's unclear how exactly it works.

By sniffing the network connection for [the demo](http://docs.webix.com/samples/17_datatree/16_dyn_loading/01_dyn_loading.html), I see that when clicking on a node, Webix sends a request with two parameters:

* `continue=true` - what exactly does this mean?
* `parent=<node ID>`

But beyond that, what should the server implementation do?

How does pagination work for nodes with many children? I see there's a [pager property for trees](http://docs.webix.com/api__link__ui.tree_pager_config.html) but the example is for `datatable`.

Does `loadahead` work like for [datatable](http://docs.webix.com/samples/15_datatable/16_dyn_loading/04_db_dyn_loadahead.html)? How about `datafetch`?

How can a proxy or function be substituted for the `url` parameter to implement dynamic tree data loading? How does `url` differ from [dataFeed](http://docs.webix.com/api__link__ui.tree_datafeed_config.html)?

It would be great to improve http://docs.webix.com/datatree__loading_data.html with this information; otherwise users may be fumbling in the dark trying to load tree data dynamically.

**Comment by dandv** [comment]
Is it possible to page loading the children for a Treeview? [In Kendo UI it's not.](http://www.telerik.com/forums/paging-a-treeview)

**Comment by Zwillinge** [comment]
All the answers you will be able to find in the updated documentation that comes with Webix 2.2 release.
