### ISSUE TITLE
Keeping this repo up to date with the main codebase

### ISSUE THREAD

**Issue by dandv** [webix-hub/tracker#182]
I see in the README from http://docs.webix.com/builds/webix.zip that the current version is 2.1.5, while the README here shows 2.1.1.

Are there any plans to keep this [code distribution repo](https://github.com/webix-hub/tracker/pull/84) in sync with the actual repo?

How about using GitHub as the main repo? The [Meteor.js project](https://github.com/meteor/meteor) does so, and it has been working very well for two years. [So does Kendo UI](https://github.com/telerik/kendo-ui-core/commits/master).

Having the actual code on GitHub allows users to submit pull requests, and shows the real work that's going into Webix. Right now, this mirror repo only has 17 commits. There are various search tools for GitHub that rank projects by the number of commits; for these, Webix will score very low.

**Comment by mkozhukh** [comment]
We will keep this repo up to date fore sure. 
It is used as source for bower package of Webix UI. 

Probably we will make the main dev. repo visible as well, but it need some time as both open-source and functionality for commercial widgets is stored in one place.

**Comment by dandv** [comment]
As the interest in Webix keeps growing, are there plans to make the open source code easier to contribute to? Right now this repo has one huge monolithic file, and I suspect the XB code is actually split into more manageable modules.

**Comment by TobyEalden** [comment]
:+1:  I'm keen to push for adoption of webix in our projects (possibly resulting in purchasing pro licences), but ATM the documentation is too poor and there are too many niggling issues in the code-base that need sorting out. Currently the time between releases is too long and there is no guarantee that issues will be fixed in the next release. Enabling contributions would mean we could stop moaning and fix the issues ourselves :)

**Comment by mkozhukh** [comment]
We plan to switch to es6 modules in version 5.0, and as part of this update we will make the real sources available on GitHub

For now, as part of this repo cleanup, I'm closing this ticket.
