### ISSUE TITLE
CORS error getting fonts for the datepicker in Snippets

### ISSUE THREAD

**Issue by dandv** [webix-hub/tracker#184]
Run a snippet that initializes a datepicker, e.g. [this one](http://webix.com/snippet/b60d5174). When the datepicker control is displayed, the following error can be seen in the console:

> Font from origin 'http://cdn.webix.io' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://webix.com' is therefore not allowed access. The response had HTTP status code 500.
webix.js:7
> GET http://cdn.webix.io/site/skins/fonts/PTS-bold.woff

**Comment by mkozhukh** [comment]
Yep, thanks for reporting the issue. 
Weill be fixed after oncoming update to Webix 2.2
