### ISSUE TITLE
User can tab out of modal windows

### ISSUE THREAD

**Issue by dandv** [webix-hub/tracker#186]
Bug demo at http://webix.com/snippet/219d87d6

**Comment by mkozhukh** [comment]
Yep, I can confirm the issue. 

As this is not real modal layer, but just an html cover other the content, it is hard to block focus on the underlying content. It is possible to block tab key processing but I think it will just irritate end users. 

On other hand, it requires just a few clicks in js console to remove modal layer, so modality can't be counted as fully safe. Advanced user will be able to bypass it anyway.

**Comment by dandv** [comment]
One way to prevent moving out of the modal is to onkeydown globally, check if the pressed key is [Tab], and if so, check the newly focused element, and move the focus back to the modal if the element doesn't belong to the modal.

Bypassing is possible indeed, but the UX improvement I'm thinking of is that if a user presses Tab multiple times, they'll cycle focus only among elements of that modal.

**Comment by mkozhukh** [comment]
We have checked the possible solutions and it seems that messing with native focusing logic will cause more harm than good. We will stay with current behavior.
