### ISSUE TITLE
Add a sample for modal Window with form inside

### ISSUE THREAD

**Issue by dandv** [webix-hub/tracker#188]
Login modal forms are pretty common. Would help to add an example for "[Modal window with form](http://forum.webix.com/discussion/3609/displaying-a-modal-form)" (e.g. http://webix.com/snippet/f084fb05 after it's fixed to work after clicking the button a second time (not there's a "script error")).

This would fit well at http://docs.webix.com/samples/10_window/index.html near "Modal box".

**Comment by Zwillinge** [comment]
The enhancement is accepted. I have modified the existing sample (http://docs.webix.com/samples/10_window/13_form.html) to make it more "speaking". 

As to the sample you've provided, you should have not closed the window, as close() method completely destroys the window, which causes script error. hide() should be used instead. 

Also, there exists a  getTopParentView() method that helps getting window object for any of the embedded views. 

You can check the updated snippet here:  http://webix.com/snippet/78e877e7
