### ISSUE TITLE
Add dynamic data loading demo to Tree

### ISSUE THREAD

**Issue by dandv** [webix-hub/tracker#189]
http://webix.com/widget/tree/ mentions dynamic data loading, but lacks a demo link.

A demo would be nice, e.g. http://docs.webix.com/samples/17_datatree/16_dyn_loading/01_dyn_loading.html

**Comment by Zwillinge** [comment]
The samples have been added with Webix 2.2 release. 
http://docs.webix.com/samples/17_datatree/16_dyn_loading/index.html
