### ISSUE TITLE
Fix CORS permissions so that Snippets can load data from docs.webix.com

### ISSUE THREAD

**Issue by dandv** [webix-hub/tracker#191]
```js
//dynamic loading
webix.ui({
  container:"testB",
  view:"tree",
  url:"http://docs.webix.com/samples/17_datatree/16_dyn_loading/data/data_dyn_json.php"
});
```

[The snippet above, on webix.com/snippets](http://webix.com/snippet/5bb90f6a), fails to load with the following error:

> XMLHttpRequest cannot load http://docs.webix.com/samples/17_datatree/16_dyn_loading/data/data_dyn_json.php. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.webix.com' is therefore not allowed access.

**Comment by mkozhukh** [comment]
Fixed,

http://webix.com/snippet/5b4b6954

**Comment by dandv** [comment]
Good step towards making the samples editable in Snippets, thanks. Or maybe the samples should simply be links to Snippets? Most devs who see the samples will want to see the code too.
