### ISSUE TITLE
Make the edition comparison tables match

### ISSUE THREAD

**Issue by dandv** [webix-hub/tracker#192]
http://webix.com/licenses/ suggests that there are no locales (probably except English) in the Standard edition. But http://webix.com/download/ shows there are 9 locales.

**Comment by mkozhukh** [comment]
Fixed. Thanks for reporting the issue

**Comment by dandv** [comment]
Thanks for the fix. On the licenses page, suggested improvement: "Our support is implemented only by Webix development team" -> "Our support is provided only by Webix development team."
