### ISSUE TITLE
BUG:  addView of Accordion fails (Accordion doesn't support refresh) 2.1.1

### ISSUE THREAD

**Issue by reynardmc22** [webix-hub/tracker#194]
Can't add an Accordion view, as refresh errors out on addview function.  The below code works fine on version 1.2, trying to upgrade to newest version and this is a show stopper.

	addView:function(view){
		var id = webix.ui.layout.prototype.addView.apply(this, arguments);
		webix.$$(id).refresh();
		return id;
	},

Testing code
		var filterPanelScrollView = { 
				view:"scrollview",
				id:"scrollViewComponent",
				width:160,
				body:{
					view:"accordion",
					multi:true,
					id:"filterPanelAccordion",
					rows:[{ type:"space" }]
				},
				scroll:"y"
		  };

	  var ui_scheme={
	   			 type:"line", id:"mainReportViewArea", view:"layout", width:200, cols:[ 
							filterPanelScrollView
	   			  ]
				};	
	
		
		
		
		webix.ready(function(){
			webix.ui(ui_scheme);
			
			for (var i = 0; i < 20; i++) {			
				var listControl = {
						view:"list",
						autoheight:true,
						scroll:false,
						select:"multiselect",
						data:["adfasdf", "asdfas","tets"]
				};
				
				template = {header:"header:" + i, body:listControl};
				var accordion = { view:"accordion", multi:true, rows:[template], collapsed:true, id:"accordian" + i};
				$$("filterPanelAccordion").addView(accordion , $$("filterPanelAccordion").getChildViews().length);
			}
		});

**Comment by reynardmc22** [comment]
Completely removing addView from the Accordion object appears to work just fine, i'm thinking this is something that wasn't meant to go here as that isn't present on version 1.2.   The parent's addView seems to work fine, think it's in baseLayout.

**Comment by mkozhukh** [comment]
I can confirm the regression. 
Deleting webix.$$(id).refresh(); line can be used as a temporary solution

This line is actually solves different issue with adding views, next build wll contain the full fix.

**Comment by mkozhukh** [comment]
Check the next snippet, it shows how your code can be simplified a bit in case of Webix 2.x
http://webix.com/snippet/4740be81

Instead of creating separate accordions it possible to add items to top level accordion ( which was not possible in Webix 1.x ) 

Your original code is still valid of course, so after next update both yours and above approaches will be valid.

**Comment by mkozhukh** [comment]
Fixed in Webix 2.2
