### ISSUE TITLE
Label not working

### ISSUE THREAD

**Issue by reynardmc22** [webix-hub/tracker#195]
Trying to use label or dynamically add a label results in label divs being created but no text being placed in the div to show on screen.  Was working in version 1.2 not working in 2.1.1.  Using a template is a good workaround.

**Comment by dandv** [comment]
Hey @reynardmc22, I got a lot more responses from @mkozhukh [on the forum](http://forum.webix.com/profile/discussions/9889/dandv). He might be busy at the moment and hasn't checked GitHub in a while.

Hope he finds some time to go through the recent GitHub issues.

**Comment by reynardmc22** [comment]
I find he usually goes through this once a release cycle at some point in time and usually fixes any major bugs that are listed in here.  This little label guy i'm not sure how they could've possible missed.  I'm in no hurry for the fixes i usually just work around them or fix their code and submit it back not a huge deal.

**Comment by dandv** [comment]
Nice. Haven't seen any PRs from you in this repo, where do you submit them?

**Comment by reynardmc22** [comment]
Oh they're all the oldest ones that are closed,  we haven't upgraded in a while but usually find 3 things broken on it, going from 1.2 to newest wasnt horrible as this is maturing more but still not super easy

**Comment by mkozhukh** [comment]
Hi,

Are you using syntax like next

```
$$("stack").addView({ view:"label", label:"123" });
```

http://webix.com/snippet/6fd9072d

I'm not sure, but probably in version 1.2 it was possible to init label by using "value" attribute instead of "label".

**Comment by reynardmc22** [comment]
The doc still has value in it so was following that,  just update documentation and it be good
