### ISSUE TITLE
DataView template not specifiable via Type property using HTML init

### ISSUE THREAD

**Issue by narcoticfresh** [webix-hub/tracker#197]
Hi guys..

First: Webix is great, thanks very much! ;-)

I implemented a DataView (Angular integrated) and it all works fine if using a normal data URL.. But because I want to use my angular resources (Models backed by REST service), I'm trying to create my own Data Proxy. I looked at the sources and tried to do it analogue to the IndexedDB proxy (I couldn't find another example which don't use webix.ajax).

For now, it should just return a static JS array. So I created this proxy:
```php
webix.proxy.angularResource = {
    $proxy: true,
    load: function (view, callback) {
        var modelName = this.source;
        var data = [
            {
                filename: 'hans.jpg',
                thumbnail: '/thumb.jpg',
                tags: 'sd, sd'
            },
            {
                filename: 'hans.jpg',
                thumbnail: '/thumb.jpg',
                tags: 'sd, sd'
            }
        ];

        view.parse(data);
        //view.render();
        webix.ajax.$callback(view, callback, "[]", data);

        return data;
    },
    save: function (view, update, dp, callback) {
    }
};
```

OK; i reference it as follows (using HTML Init):
```html
<div id="itemList" view="dataview" css="item-view" borderless="true" url="angularResource->Media"
  webix-event="onBeforeRender = itemListRender(id, details)" datafetch="50">
</div>
```

What happens now, is strange: The proxy gets executed (good) and the records get fetched - I see the child nodes inside the DOM that got created. 
But it's only visible in the browser after I resize the browser window!

How can it be? Is there an event or function on the view I need to call? I tried to call ``view.render()``, no success..
How come it gets shown on window resize?

Any ideas?
Thanks

**Comment by mkozhukh** [comment]
Hi, 

The same code works for me 

Js init - http://webix.com/snippet/a3fbc984
HTML init - http://webix.com/snippet/186027f7

( i have added the "template" attribute to show some visible text, but all other code is the same as in your case ) 

By default component will try to adjust self to the size of parent HTML container. Try to set some fixed height on the top-most html container and check will it help or not.  ( something like here http://webix.com/snippet/80d1e668 )

By the way, the code of proxy is fully correct, so problem must not be related to the data loading.

**Comment by narcoticfresh** [comment]
Hm, yes.. I see it works in that isolated test case.. That's strange. I tried to show my (more complex) use case here, but it doesn't render, and I can't see what's wrong => http://webix.com/snippet/6eb3d1eb

I do 2 unusual things
* Somehow I didn't know how to define the "type" attribute on the dataview in html.
* Also the template somehow wouldn't show when defined through HTML (i tried just defining a sub-div of the dataview-div or a type="template" div..

So what I do is to use a callback to set those attribute on top of the html init.
Attach on beforeRender:
```html
<div ... webix-event="onBeforeRender = itemListRender(id, details)" datafetch="50"></div>
```
and then: 
```js
    $scope.itemListRender = function (id, details) {
        $$('itemList').define('type', {height: 200, width: 250});
        $$('itemList').define('template',  " <div class='item-wrapper'> " +
    " <div><img src='#thumbnail#' class='item-thumbnail' /></div> " +
    " <div class='item-tags'>#tags#</div> " +
    " </div>");
    };
```

As said: My problem is not, that the proxy doesn't get used. After rendering I see exactly 2 child nodes under the dataview (same amount as records defined in the demo proxy), but indeed with odd css (that's one of the 2 nodes):
```html
<div webix_f_id="1421788376548" class="webix_dataview_item " style="width:160px; height:50px; float:left; overflow:hidden;">
            </div>
```
As i resize the window, they get immediately drawn to (same node after window resize):
```html
<div webix_f_id="1421788376548" class="webix_dataview_item " style="width:250px; height:200px; float:left; overflow:hidden;"> <div class="item-wrapper">  <div><img src="/thumb.jpg" class="item-thumbnail"></div>  <div class="item-tags">sd, sd</div>  </div></div>
```
OK; not the template is visible with the data from the proxy.

So it's there - somehow, but the template and/or type attribute aren't working..

**Strange is,**, using a the normal URL approach (normal webix.ajax) works exactly like this, even using this bad workaround way of setting type & template.. somehow rendering and/or data processing is different using a proxy object(?).. I didn't try another proxy object though..

Hmm...

**Comment by narcoticfresh** [comment]
Hello again

First of all, webix seems to be in Bower again, thanks! (although still @version 2.1.1)

Back to this issue..

I tried around a bit and cleanup up the beforeRender mess (which I think is not the way to go)  I've had to solve my problem differently - I edited the issue title accordingly.. 

I've seen that the Type property can be defined in code and referenced in HTML. That's perfect for my case - but there seems to be an issue that the template can't be specified in the Type, it only works as HTML attribute.

I created two snippets to demonstrate that:
Type created; template as html property (works): http://webix.com/snippet/ebaed8ee
Type created; template as property in Type instance (doesn't work): http://webix.com/snippet/92c4ea98

If the template specified as Type property (object in code) isn't supposed to work in the first place, consider the issue closed - I can also specify it as HTML attribute. But as I read the documentation of the Type implementation, I guess this should be possible..

Thanks again!

**Comment by mkozhukh** [comment]
Thanks for provided snippets. 
I can confirm two problems with dataview

a) issue with missed template ( in case of template attribute and in case of Type.template ) 

While initializing from HTML markup, component takes content of tag as template. So you need to have template in the tag
http://webix.com/snippet/2fd1c406

or you need to have the empty tag
http://webix.com/snippet/1898aa75

In you case tag is not really empty ( it contains a new-line and white-spaces ) so this empty values redefines the one set by Type.template 

I think we will change it in the next build to ignore such combination of new-lines and white-spaces,

b) There is a problem with dataview rendering, it can skip rendering if size of view is too small. In your original code you can try to change logic of load like next

```js
    load: function (view, callback) {

        var data = [
            {
                filename: 'hans.jpg',
                thumbnail: '/thumb.jpg',
                tags: 'sd, sd'
            },
            {
                filename: 'hans.jpg',
                thumbnail: '/thumb.jpg',
                tags: 'sd, sd'
            }
        ];

        view.parse(data);

        view.render();
        webix.delay(view.render, view)

        return data;
    },
```

webix.delay line will fix the issue for now. In next build we will update the component itself, so it will render self correctly without relation to the size or visibility.
