### ISSUE TITLE
BUG: Button setValue sets value no Label no setLabel function

### ISSUE THREAD

**Issue by reynardmc22** [webix-hub/tracker#199]
There is no value in the Button component.  

getValue/setValue need to be changed to getLabel/setValue and change the label on the config.

**Comment by reynardmc22** [comment]
imageButtonTop
imageTop
IconTop
iconButtonTop

Look to have the issue, imageTop is the one i am working with as imageButtonTop rendered vastly different for me from 1.2 to 2.1.   

Changes i made to the button control are below, there are other functions that should be corrected as well as the documentation.  These are just quick changes to get my project working and have not been tested with other configuration types.

	setLabel:function(value){//findme: bug fix
		var oldvalue = this._settings.label;
		if (oldvalue == value) return false;
		
		this._settings.label = value;
		if (this._rendered_input)
			this.$setLabel(value);

		this.callEvent("onChange", [value, oldvalue]);
	},

	$setLabel:function(value){
		this._settings.label = value;
		(this.getInputNode()||{}).innerHTML = value; 
	},
	getInputNode: function() {
		return this._dataobj.getElementsByClassName('webix_img_btn_text')[0];
	},

**Comment by mkozhukh** [comment]
In latest version of Webix getValue and setValue already changes the label of button. I agree that naming is a bit confusing here. Button is a base for all inputs, so while button itself doesn't have a value it still need to have getValue and setValue methods for successor components. 

Also, to set label you need not introduce the new method

```js
/*this code works for any input*/
$$("b1").config.label = "New label";
$$("b1").refresh();
```

http://webix.com/snippet/68633d9e
