### ISSUE TITLE
Feature Request:  Ability to change head value on Window

### ISSUE THREAD

**Issue by reynardmc22** [webix-hub/tracker#200]
Currently doesn't appear there is anyway to change the head on a window once it's been created.  This is the easiest way i have found to modify it

$$('window')._head_cell.config.template = function(obj) { return "Head on window"; };

**Comment by mkozhukh** [comment]
Yep, it seems to be missed in the documentation

You can use $$("window").getHead() to get header and as default header is "template" - you can use any API of template view

win.getHead().setHTML("123");

http://webix.com/snippet/c13a9d02

**Comment by Zwillinge** [comment]
Updated.
