### ISSUE TITLE
Artificially high div/body height in TreeTable samples

### ISSUE THREAD

**Issue by dandv** [webix-hub/tracker#203]
At http://docs.webix.com/samples/15_datatable/30_treetable/08_edit.html, the div is declared to be 600px tall.

![image](https://cloud.githubusercontent.com/assets/33569/5973743/afdf85fa-a820-11e4-8444-a973d4da2fe2.png)

 This is unnecessary and causes a scrollbar to appear when embedding the sample in an iframe:

[![bad scrollbar](https://cloud.githubusercontent.com/assets/33569/5973776/322ecdd6-a821-11e4-9488-b5d2d2080231.png)](http://slides.com/dandv/build-great-meteor-uis-without-html#/2/2)

This applies to other samples, e.g.
http://docs.webix.com/samples/15_datatable/30_treetable/09_item_checkbox.html
and probably to many other ones.

I think the sample itself should not make assumptions about the height of its container, and instead let the parent/caller do that.

Similarly, the `body` height is set to 100% in this sample:
http://docs.webix.com/samples/15_datatable/30_treetable/14_colspan.html
This also creates an unnecessary scrollbar when embedding the sample in an iframe.

I'm making presentation to spread the word about Webix, so fixing this little thing will help a lot :)

**Comment by Zwillinge** [comment]
Fixed

**Comment by dandv** [comment]
Thanks, will wait for push. The slide that embeds that treetable is http://slides.com/dandv/build-great-meteor-uis-without-html#/2/2. I've embedded other components (if you navigate up/down from that slide) and they work well.
