### ISSUE TITLE
Switching between views in multiview

### ISSUE THREAD

**Issue by AlyonaSizova** [webix-hub/tracker#205]
1). open link: http://vh.dev-cop.com/coins/gantt/;
2). try to switch between views (daily/weekly buttons);
3). cells in daily view becomes the same as in the weekly view.

**Comment by mkozhukh** [comment]
Not a bug actually. 

You have 2 DataTables but they are sharing the same columns object

```js
$$("rows2").config.columns[1] == $$("rows").config.columns[1]
```

So when you are setting width for columns in one of datatable, it is applied to the second one as well.
