### ISSUE TITLE
checkboxes don't work in the data table

### ISSUE THREAD

**Issue by AlyonaSizova** [webix-hub/tracker#207]
try to check some checkboxes, they become unchecked:
http://vh.dev-cop.com/coins/gantt/

**Comment by dandv** [comment]
It would help if you could post a minimal code reproducing the bug at http://webix.com/snippet. Thanks!

**Comment by mkozhukh** [comment]
Instead of custom template with checkbox inside, try to use a built-in solution

```
template:"{common.checkbox()}"
```

http://webix.com/snippet/811a40e6

**Comment by mkozhukh** [comment]
By the way, there is an issue with "inline-checkbox" editor in latest chrome. It will be fixed in Webix 2.2.4
