### ISSUE TITLE
BUG:  hidden accordianItem on initialization can not be shown

### ISSUE THREAD

**Issue by reynardmc22** [webix-hub/tracker#208]
On accordionItem if hidden:true is set on the initialization of the object, it cannot be shown afterwards, as parent_cell is null and the show() method tries to appendChild which doesn't exist.  This exists in version 2.2.3 and was not present in earlier versions.   For sure 1.0.1 it was working in, and from there i can't verify what version it stopped working.  Below is a working example of how to trigger the bug.

		 var filterPanelScrollView = { 
		            view:"scrollview",
		            id:"scrollViewComponent",
		            body:{
		                view:"accordion",
		                multi:true,
		                id:"filterPanelAccordion",
		                rows:[{ type:"space" }]
		            },
		            scroll:"y"
		      };

		  var filterPanel = {
		            id:"filterPanel",
		            view:"accordion",
		            multi:true,
		            cols:[ { header:"Filters", view:"accordionitem", id:"filterPanelLayoutAccodrion", body:filterPanelScrollView } ]
		        };

		  var ui_scheme={
		         type:"line", id:"mainReportViewArea", view:"layout", width:200, cols:[ 
		              filterPanel
		          ]
		        };  

		    webix.ready(function(){
		        webix.ui(ui_scheme);

		        for (var i = 0; i < 10; i++) {          
		            var listControl = {
		                    view:"list",
		                    autoheight:true,
		                    scroll:false,
		                    select:"multiselect",
		                    data:["adfasdf", "asdfas","tets"]
		            };

		            template = {header:"header:" + i, body:listControl};
		            var accordion = {id:"accordion" + i, view:"accordion", multi:true, rows:[template], collapsed:true, hidden:true };
		            $$("filterPanelAccordion").addView(accordion , $$("filterPanelAccordion").getChildViews().length -1);
		        }
		        for (var i = 0; i < 10; i++) {          
		        	$$("accordion" + i).hide();
		        }
		        for (var i = 0; i < 10; i++) {          
		        	$$("accordion" + i).show();
		        }

		    });

**Comment by mkozhukh** [comment]
Fix will be included in Webix 2.3
