### ISSUE TITLE
Unable to bind Carousel to DataView?

### ISSUE THREAD

**Issue by narcoticfresh** [webix-hub/tracker#213]
Hi..

According to the docs. ui.carousel is bind-able.. But I'm struggling to use that ;-) I created a snippet where i try to bind a carousel to a DataView: http://webix.com/snippet/4351b5e8

First is, it seems I need to define either "cols" or "rows" on carousel on initialization - it those are not defined, it doesn't initialize..

I tried to define the onBindRequest event to see if it triggers - it doesn't sadly.. also when I call ``$$(carouselId).bind($$(targetId), function(master, slave) {})`` - my callback never seems to get called either. So it seems, carousel doesn't even try to properly bind(?)

Maybe this makes sense as I defined ``rows: []`` so it already "has" data - but again, I need to specify that (can't also be ``null``) or it won't initialize..

Should this use case be possible? If so, what am I doing wrong? ;-)

Thanks so much for helping..

**Comment by Maria-Staskova** [comment]
Hi,

Sorry for the misleading information in our docs. Carousel is not DataStore-based view and therefore, it  does not support bind/unbind methods. We will remove these methods from our docs. 
Carousel view contains layout where you can define rows or cols you need,
