### ISSUE TITLE
any key typed in Filter also activates view.edit(pos)

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [webix-hub/tracker#214]
When i use filters in combination with the following, typing any key in my filter bar activates this code.

	webix.UIManager.addHotKey("any", function(view){
				var pos = view.getSelectedId();
				view.edit(pos);
			},  $$("myview"));

**Comment by mkozhukh** [comment]
This is expected behavior, hotkey handler will fire every time when hot-key is pressed. It doesn't matter is cursor is in the filter input or not. 

You can use second parameter of callback to check for which area hotkey was called

```js
webix.UIManager.addHotKey("any", function(view, ev){
            //filter or text editor
            if ((ev.target||ev.srcElement).tagName == "INPUT") return;

            //any other source
            var pos = view.getSelectedId();
            view.edit(pos);
        },  $$("myview"));
```
