### ISSUE TITLE
Text Edit remains open when Filter changed

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [webix-hub/tracker#215]
Edit box remains open if filter is changed while editing

![image](https://cloud.githubusercontent.com/assets/4387023/6943271/e2ba75ec-d85a-11e4-9983-0e5a5b40dc3a.png)

**Comment by mkozhukh** [comment]
I can't reconstruct the issue. Please check the next snippet

http://webix.com/snippet/521a3ae5

Please adjust it or provide your own demo where problem can be checked.

**Comment by PhaedrusTheGreek** [comment]
Demo set up here:
http://demo.elasticsheets.org/

**Comment by mkozhukh** [comment]
I can confirm issue, it occurs only when server side filtering is used.   
Fix will be included in the next public build

**Comment by mkozhukh** [comment]
Fixed in latest Webix 2.3.6
