### ISSUE TITLE
Static context menu

### ISSUE THREAD

**Issue by AlyonaSizova** [webix-hub/tracker#217]
http://webix.com/snippet/09fef9fd
1. open link
2. Right click on any cell in dt
3. Scroll a page
Result: context menu is static
Exp.result: Context menu moves with a cell

**Comment by mkozhukh** [comment]
Unfortunately this feature is by design, we do not plan  to fix it.

**Comment by dandv** [comment]
I understand this won't be fixed, but it would be nice to anchor the context menu to the cell.

If that's difficult, maybe hide the context menu on scroll?

**Comment by mkozhukh** [comment]
When we have  a single scrollbar on a page it is not a problem. But when we have a multiple scrollbars ( scrollbar of page, scrollbar of scrollview, inner scrollbar of datatable ) the situation becomes rather complicated. 

You can always use an event of datatable to force contextmenu hiding

```
dtable.attachEvent("onScrollY", function(){ webix.callEvent("onClick", []); })
```
