### ISSUE TITLE
static combo

### ISSUE THREAD

**Issue by AlyonaSizova** [webix-hub/tracker#218]
http://webix.com/snippet/0fc452f1

1. open link
2. Double click on a right cell
2. Scroll a page
Result: dropdown menu is static
Exp.result: dropdown menu follows a cel

**Comment by mkozhukh** [comment]
You can use onScroll event handler to trigger dtable.editStop. It will close the select editor popup on scrolling in the datatable. 

There is no way to auto-update position of popup element during the scrolling

**Comment by mkozhukh** [comment]
For now you can use something like 

```
dtable.attachEvent("onScrollY", function(){ webix.callEvent("onClick", []); })
```

to close all popup elements on scrolling in datatable. 

We will look how it can be improved in next versions
