### ISSUE TITLE
Skin versions mismatch?

### ISSUE THREAD

**Issue by dandv** [webix-hub/tracker#221]
https://github.com/webix-hub/tracker/blob/master/codebase/webix.css is at v2.3.8, but [all other skins](https://github.com/webix-hub/tracker/tree/master/codebase/skins) are at v2.3.6.

**Comment by mkozhukh** [comment]
There were no updates in CSS files between v2.3.8 and v.2.3.6 
Anyway, all of them at version 2.3.14 now.
