### ISSUE TITLE
invisible tooltip

### ISSUE THREAD

**Issue by AlyonaSizova** [webix-hub/tracker#227]
http://webix.com/snippet/301cf766

try to hover cursor over the rightmost column. result: http://prntscr.com/75j1q9

**Comment by ilyabasiuk** [comment]
Have the same problem with tree 
http://webix.com/snippet/cdde288e
http://screencast.com/t/Fav0JUSxt5

**Comment by HannaBabrouskaya** [comment]
@AlyonaSizova @ilyabasiuk fixed and will be available in the next version
