### ISSUE TITLE
Certain methods/properties of a component do not show up in the documentation

### ISSUE THREAD

**Issue by igorsousa-b** [webix-hub/tracker#228]
As the title says. Some methods such as getColumnConfig() do not now show up in datatable's documentation. It only shows up in treetable's page, even though it works on both. There are probably more examples of this.

(not sure how to add labels, but this should be marked as documentation)

**Comment by dandv** [comment]
:+1: . The documentation needs a lookover from a professional editor. See also #178.

**Comment by Maria-Staskova** [comment]
@igorsousa-b,  @dandv we appreciate your feedback. The issue with methods was solved. We keep working on improving our documentation.
