### ISSUE TITLE
Suggestion: use Code Snippet for Samples

### ISSUE THREAD

**Issue by igorsousa-b** [webix-hub/tracker#229]
As is, samples are just a page with nothing but the component being shown. If a user wants to see the code behind, they need to use some sort of inspector tool to do this. If the samples linked to a Code Snippet with said sample, it would be much less of a hassle with the added benefit of being able to tinker with the code on the fly.

**Comment by dandv** [comment]
:+1: . I think I [suggested this on the forum too](http://forum.webix.com/discussion/3645/suggestion-add-a-button-to-run-samples-in-snippets).

**Comment by mafanya23** [comment]
Now docs and API pages are provided with links to snippets, while folders with samples are still available on the documentation site.
