### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by matthewfl** [webix-hub/tracker#231]
I am not 100% sure about this, but afaik licensing your code under the GPL requires that you also publish the source code.

Reading the included copy of the GPLv3, the [source code](https://github.com/webix-hub/tracker/blob/master/license.txt#L114-L116) is defined as

```
  The "source code" for a work means the preferred form of the work
for making modifications to it.  "Object code" means any non-source
form of a work.
```

Based off what I see in this repo, you appear to be distributing the javascript in a [object form](https://github.com/webix-hub/tracker/blob/master/codebase/webix.js) which would fall under the [Conveying Non-Source Forms.](https://github.com/webix-hub/tracker/blob/master/license.txt#L245) section, which basically says that there needs to be some way to access the source code.

**Comment by dandv** [comment]
There's [webix_debug.js](https://github.com/webix-hub/tracker/blob/master/codebase/webix_debug.js).

**Comment by matthewfl** [comment]
ehhh, that is not something that I would want to edit if I were to make a change.

I am assuming that this is generated from a number of files which have a nice logical structure/layout to them

**Comment by dandv** [comment]
Correct, it's generated from their repo which has both the OSS and the Pro version.

**Comment by matthewfl** [comment]
Right, so afaik given that this is under the GPL, at least the files that are used from the repo to generate the OSS version should be distributed somewhere.

**Comment by dandv** [comment]
Ping @mkozhukh since he's just published v2.4.7.

**Comment by matthewfl** [comment]
ping @kelluvuus @mafanya23 @Maria-Staskova @mkozhukh @Zwillinge ?

**Comment by dandv** [comment]
I've left a comment at http://webix.com/blog/using-webix-in-open-source/ pointing to this issue.

**Comment by matthewfl** [comment]
Hm, that is a fairly strange blog article.  It sounds like they are trying to just make the GPL more permissive.  Given that one can use this code with a MIT or BSD licensed project, I believe that one could create a "shell" project under the MIT license that includes this code and then include that into a closed source property project without being in violation of their "FLOSS exception" or their now "modified GPL".

Assuming that they actually meant to write that FLOSS exception it might more since to license this under the [LGPL](https://www.gnu.org/licenses/lgpl-3.0.en.html) instead of the "GPL with modifications" since it already includes exceptions sorta like that.

Based off what I am guessing what webix is trying to do, in terms of sell professional license for closed source exceptions, I think that they were mostly doing it right before with having their code under the GPL and then having some license that can be bought.  But looking at other companies that adopt this model, they also end up releasing their source code given the terms of the GPL.

Finally, I just want to say that the above is just based off my own reading/understanding of these license and in no way represents a "legal/professional opinion."  I am mostly interested in using this a small personal project and was interested in viewing the source code to see if I could strip out components that I wasn't going to use (things that one normally expects to be able to do to a GPL project).

**Comment by dandv** [comment]
Let's see what more legally versed individuals say:

http://opensource.stackexchange.com/questions/900/does-licensing-javascript-code-under-the-gpl-require-publishing-the-non-concaten

**Comment by mkozhukh** [comment]
> Right, so afaik given that this is under the GPL, at least the files that are used from the repo to generate the OSS version should be distributed somewhere.

According to GPL v3, "Corresponding Sources" is an "all the source code needed to generate, install, and (for an executable work) run the object code and to modify the work". webix_debug.js contains all the source code and allows modification ( it is not compressed, and not obfuscated in any way ) 

Actually, I don't mind to share the low-level source files, which we are using locally. I just don't see how it benefit anyone.

**Comment by mkozhukh** [comment]
We clearly understand that GPL is not compatible with many other OSS licenses, which limits a usage of Webix in OSS projects. In the same time, we can't switch Webix itself to MIT or similar permissive license.

FLOSS Exception was added to resolve this conflict. It allows to use the product under most OSS licenses, and it preserves the GPL vs Commercial choice for closed source projects. As far as I can see this is a Win-Win situation.

By the way, this exception is not our invention, a similar exception is used by MySQL, ExtJS and some other projects. 

>I believe that one could create a "shell" project under the MIT license that includes this code and then include that into a closed source property project

Not really, it is covered by the next text in the FLOSS Exception "The Derivative Work can reasonably be considered independent and separate work that is intended for use by end-users and not as a library for software development purposes.". 

So this exception doesn't allow you to create a set of  dev. tools under MIT license, which later can be included in the closed source project.

**Comment by mkozhukh** [comment]
We plan to switch to es6 modules in version 5.0, and as part of this update we will make the real sources available on GitHub

For now, as part of this repo cleanup, I'm closing this ticket.
