### ISSUE TITLE
Popups position

### ISSUE THREAD

**Issue by zaitsev-roman** [webix-hub/tracker#233]
http://webix.com/snippet/e154583c
Follow steps:
1. Open snippet.
2. Click combo/datepicker to open suggest list.
3. Resize browser to half of width.

Result: suggest list goes out of combo/datepicker. (http://prntscr.com/7jvdms)

**Comment by mkozhukh** [comment]
Yep, I can confirm the issue.

As quick solution try to add the code like next

```
    webix.event(window, "resize", function(){
      webix.callEvent("onClick", []);
    })
```

http://webix.com/snippet/72c40d20
