### ISSUE TITLE
Combo suggest list bug

### ISSUE THREAD

**Issue by zaitsev-roman** [webix-hub/tracker#236]
http://webix.com/snippet/b71283a8

1. Follow top link
2. Click on combo to open suggest list
3. Click on button

Result: combo dissapear but suggest list pointer still exists on page.
Expected result: all elements of combo dissapears.

I can handle this situation.
 But it is strange when I remove combo from DOM and pointer still exists.
![bugg](https://cloud.githubusercontent.com/assets/2146727/8545923/edaed71a-24bb-11e5-8b00-71e893077083.png)

**Comment by mkozhukh** [comment]
Yep, I can confirm the issue, fix will be included in the next build
