### ISSUE TITLE
What does loadStaskova mean?

### ISSUE THREAD

**Issue by dandv** [webix-hub/tracker#245]
In [whatsnew.md](https://github.com/webix-hub/tracker/blob/master/whatsnew.md):

> refreshing data in select-based filters on options loadStaskova

**Comment by dandv** [comment]
@Maria-Staskova: I've seen you've been closing many bugs, which it great. It would also help contributors feel their issues or fixes have been valuable if you added a few words about the closing reason, or at least the "fixed" label.

Thanks!

(Here's what I see right now; no idea how/why the issue was closed - fixed? invalid? etc.)

![image](https://cloud.githubusercontent.com/assets/33569/13401361/aade63d2-dec0-11e5-9f25-ac3c5ca8c86c.png)

**Comment by Maria-Staskova** [comment]
Hi Dan,

Sorry! You are absolutely right. All closed issues were fixed. I'll set correct status or leave some comments.

**Comment by dandv** [comment]
Thank you!
