### ISSUE TITLE
Portlet reconstruct() loses the drag/drop on header obj

### ISSUE THREAD

**Issue by reynardmc22** [webix-hub/tracker#251]
Portlet reconstruct() loses the drag/drop on header obj

**Comment by reynardmc22** [comment]
._init_drag_area();

that isn't called when reconstruct is done thus losing the dragarea.   Creating a local reconstruct() method to do that after the super is called works,  

also how do you change the header on these guys? getHead doesn't seem to work well,

**Comment by HannaBabrouskaya** [comment]
@reynardmc22 cannot reproduce this bug in actual webix version. 
You can access portlet header for example through portlet $view:
$$("portlet").$view.firstChild
