### ISSUE TITLE
german translation

### ISSUE THREAD

**Issue by akralj** [webix-hub/tracker#256]
hI,
https://github.com/webix-hub/tracker/blame/a7f9c52401b2dfd944c7874e35a3559838a3ed9a/codebase/i18n/de.js#L27
the following terms are not really idomatic in german ui interfaces:
done:"Bereit",
clear: "Klären",

so i suggest:
done: "OK"
clear: "Löschen" 

clear is really difficult to translate, because it depends on the context and there is usually not one german word to translante to.
clearing a form: "Eingaben löschen".
what is the context in datepicker?

**Comment by Maria-Staskova** [comment]
Hi,

thank you for remarks. We will update the german translations as follows:

done=> "Fertig"
clear=> "Entfernen"

>> what is the context in datepicker?

The context is the same as "clear" for a form
