### ISSUE TITLE
There is no possibility to reset invalid message for field

### ISSUE THREAD

**Issue by ilyabasiuk** [webix-hub/tracker#261]
Hi. 

Here is the link :
http://webix.com/snippet/d8e75dac

You should only wait for 2 seconds to get the error).

Expected result: Form should not have any red highlighted fields and no error messages
Actual result: We have error message for the first field. It's not highlighted with red, but it exists.

**Comment by mkozhukh** [comment]
Will be fixed in Webix 3.3
