### ISSUE TITLE
Scroll position changes after updating data in the table

### ISSUE THREAD

**Issue by ilyabasiuk** [webix-hub/tracker#263]
Hi. 
Here is the demo:
http://webix.com/snippet/e3eb590b

Steps to reproduce: 
1. Scroll down the page to the bottom
2. Click update button

Result: Scroll changed it's position and now we are not able to see the table any more :(
Expected result: Scroll will be on the same place

Thanks, 
Ilya

**Comment by mkozhukh** [comment]
Not a bug. 

When you are calling .cleaAll, grid is cleared, and as it has an autoheight option, parent scrollview is adjusted to the new size. You can try to use webix.ui.$freeze flag to prevent UI resizing for a group of operations. 

http://webix.com/snippet/86410625

**Comment by ilyabasiuk** [comment]
Is it any possibility to update table data whitout calling clearAll method?
