### ISSUE TITLE
Isolated popup isn't destructed after close

### ISSUE THREAD

**Issue by ilyabasiuk** [webix-hub/tracker#265]
Hi. 
Here is 2 ways to create popup: in global space and in isolated. 

http://webix.com/snippet/28c36f05

Expected result: Isolated popup should destoyed after close like popup  created in global space
Result: We still could get isolated popup.

**Comment by mkozhukh** [comment]
Not a bug. 

When you are calling .cleaAll, grid is cleared, and as it has an autoheight option, parent scrollview is adjusted to the new size. You can try to use webix.ui.$freeze flag to prevent UI resizing for a group of operations. 

http://webix.com/snippet/86410625

**Comment by mkozhukh** [comment]
Will be fixed in Webix 3.3
