### ISSUE TITLE
Error after attempt to hide column in ui.datatable 

### ISSUE THREAD

**Issue by ilyabasiuk** [webix-hub/tracker#269]
Hi,

Steps: 
1. "Hide 'Group 1'"
2. "Hide subgroups 'B'"

http://webix.com/snippet/bc6f8267

Result: webix_debug.js:17503 Uncaught TypeError: Cannot read property 'header' of undefined
Expected: no error )

**Comment by mkozhukh** [comment]
Fix will be included in Webix 3.3
