### ISSUE TITLE
Ui.combo doesn't apply my selection after clicking Enter button

### ISSUE THREAD

**Issue by ilyabasiuk** [webix-hub/tracker#272]
Hi. 

http://webix.com/snippet/2fbb8262

Steps:
1. Go to colbo field and delete "Banana" from it
2. Type "PA"
3. Click Enter button

Expected result: "PA" id 4 will be selected in combo
Result: selction resored to previous state "Banana"

**Comment by Maria-Staskova** [comment]
Fixed in Webix 3.3
