### ISSUE TITLE
IdSpace: resize required to see updated isolted view

### ISSUE THREAD

**Issue by ilyabasiuk** [webix-hub/tracker#274]
Hi,

http://webix.com/snippet/e097a0b5

**Comment by mkozhukh** [comment]
Issue occurs only if you are using the empty layout at start, for non-empty layout issue doesn't occur
http://webix.com/snippet/ef0c6b56

Providing fixed height or autoheight, will solve issue as well
http://webix.com/snippet/7e031361

With the original code, datatable has not any requirements for the height, so it take the zero height from the empty layout. It is correct behavior, for the current sizing logic. We plan to add a more flexible sizing in Webix 4.0 Till that version, please use one of above workarounds.
