### ISSUE TITLE
DataTable default pager layout

### ISSUE THREAD

**Issue by Spoonin** [webix-hub/tracker#278]
Looks like a datatable pager is not a part of layout so it pushes the datatable footer out of the block:
[pager presents](http://webix.com/snippet/9cc00174)
[no pager - no issue](http://webix.com/snippet/612a6b83)

**Comment by mkozhukh** [comment]
If you are using full-screen layout, it is expected that you will provide a place for the pager in the layout
Check the next snippet

http://webix.com/snippet/a4e4adc3

If you are not providing container to layout, it will be attached to the DOM directly, which may break sizing of other views.
