### ISSUE TITLE
Hide columns bug

### ISSUE THREAD

**Issue by zaitsev-roman** [webix-hub/tracker#280]
Please, follow next steps:
1. Go http://webix.com/snippet/539a9c2d
2. Scroll table maximum to the right
3. Press button hide cols

Result: http://prntscr.com/bk53ff
Expected result: no console errors.

Tables with colspan and rowspan have broken headers when this bug occurs .

**Comment by HannaBabrouskaya** [comment]
@zaitsev-roman fixed and will be available in the next webix version
