### ISSUE TITLE
After changing the type of tree the css applyed by old type is not removed

### ISSUE THREAD

**Issue by ows-nightwolf** [webix-hub/tracker#281]
Demo: [http://webix.com/snippet/2260f70a](http://webix.com/snippet/2260f70a)

Description: Suppose we need to create the tree with several representation types (in demo: with 'default' and 'detailsView'), each type has its own css class (in demo: 'detailsView' type has css class 'detailsView'), and we need to switch between this views on the fly. Issue: after switching view the css class related to old (deleted) view is not removed.

Expected behaviour: The old css class is removed.

Tested in: IE, Firefox, Chrome

**Comment by HannaBabrouskaya** [comment]
@ows-nightwolf for your issue you can use http://docs.webix.com/api__link__ui.tree_removecss.html 
Example: http://webix.com/snippet/58159901
