### ISSUE TITLE
Dynamic UI modifications with isolated id's

### ISSUE THREAD

**Issue by ows-nightwolf** [webix-hub/tracker#282]
Demo: [http://webix.com/snippet/d3504986](http://webix.com/snippet/d3504986)

Description: Suppose we need to toggle the subview of given view (which has the property 'isolate' that equals 'true') on button click. As you can see in the demo the subview toggles only once.

Expected behaviour: The view toggles every time you click on the button.

Tested in: IE, Firefox, Chrome

**Comment by HannaBabrouskaya** [comment]
@ows-nightwolf in this case there is no need for 'isolate'. Working variant should look like this http://webix.com/snippet/413dddba
If you want to use property 'isolate' for layout, it should be applied to every item(row/col) you want to isolate. Please, check this [example](http://webix.com/snippet/c4624491)
