### ISSUE TITLE
New method for dynamic modifications in carousel

### ISSUE THREAD

**Issue by avasuro** [webix-hub/tracker#283]
Demo: [http://webix.com/snippet/99dafb4b](http://webix.com/snippet/99dafb4b)

At the moment, if you want to dynamically change the contents of the 'Carousel' component, you have to replace the entire carousel view with the new carousel view, with necessary items (see changeLayout function in demo). It would be nice to have a method that allows changing content of the carousel without creating it entirely from scratch.

**Comment by HannaBabrouskaya** [comment]
@ows-nightwolf new methods like addView and removeView will be available in webix 4.4

**Comment by HannaBabrouskaya** [comment]
@avasuro added methods: https://docs.webix.com/api__ui.carousel_addview.html and https://docs.webix.com/api__ui.carousel_removeview.html
