### ISSUE TITLE
Error when "setActive" method of carousel view called

### ISSUE THREAD

**Issue by ows-nightwolf** [webix-hub/tracker#287]
Demo: [http://webix.com/snippet/1f24aed7](http://webix.com/snippet/1f24aed7)

Description: If carousel view nested in some component (for example, layout) with property `isolate: true` its method 'setActive' throws an error "TypeError: Cannot read property 'show' of undefined".

Expected behaviour: 'setActive' method shouldn't throw an error.

Tested in: IE, Firefox, Chrome

**Comment by HannaBabrouskaya** [comment]
@ows-nightwolf the reason is that element with id "test" cannot be found in global scope because of isolate propery set to true. This is an expected behavior for 'isolate'.
But you can pass element like [this](https://webix.com/snippet/d4f21493)
