### ISSUE TITLE
compact.css - Not vertically centerd due to "line-height: 1" for menu item

### ISSUE THREAD

**Issue by visvadw** [webix-hub/tracker#289]
Hello Webix team,

While playing with the result of Webix Jet bootstrap tool (`wjet init`), I've noticed that the menu items `span` child gets a `line-height: 1` and thus the items are top-aligned instead of being vertically centered.

![image](https://cloud.githubusercontent.com/assets/14140226/18061573/e645285c-6e2b-11e6-8acf-8df6bd47d2b9.png)

Thanks.

**Comment by HannaBabrouskaya** [comment]
@visvadw fixed
