### ISSUE TITLE
Dataview empty content when height: "auto"

### ISSUE THREAD

**Issue by schongo** [webix-hub/tracker#290]
since webix 2.5.0 there seems to be a bug that renders an empty Dataview when type.height == "auto" (or "autoheight" == true). The effect can be seen in the "official" sample:

http://docs.webix.com/samples/06_dataview/01_initialization/04_content_sizing.html

With Webix 2.4.7 it works.

**Comment by HannaBabrouskaya** [comment]
@schongo cannot reproduce it. Could you, please, provide a snippet which reproduces this bug?

**Comment by HannaBabrouskaya** [comment]
Not confirmed
