### ISSUE TITLE
wrong email validation

### ISSUE THREAD

**Issue by ows-nightwolf** [webix-hub/tracker#291]
**Demo:** [http://webix.com/snippet/380f0d5c](http://webix.com/snippet/380f0d5c)

**Description:** in the e-mail field insert only spaces before @ (or in any other part of the e-mail address). The Email field passes validation, but indeed it's not valid.

**Expected behaviour:** Email address doesn't pass the validation.

**Tested in:** IE, Firefox, Chrome

**Comment by HannaBabrouskaya** [comment]
@ows-nightwolf fixed and will be available in the next version
