### ISSUE TITLE
Wrong calendar data

### ISSUE THREAD

**Issue by ows-nightwolf** [webix-hub/tracker#292]
**Demo:** [http://webix.com/snippet/f382b343](http://webix.com/snippet/f382b343)

**Description:** click on the calendar's title (where current month and year is showing), than click it again - it'll show you calendar with years from 2009 to 2020, but in the calendar's header displays '2009-2019'. [http://prntscr.com/chwq1w](http://prntscr.com/chwq1w)

**Expected behaviour:** In the calendar header should be shown '2009-2020'

**Tested in:** IE, Firefox, Chrome

**Comment by HannaBabrouskaya** [comment]
@ows-nightwolf fixed and will be available in the next version
