### ISSUE TITLE
Treetable checkboxes brake template

### ISSUE THREAD

**Issue by Spoonin** [webix-hub/tracker#293]
At your example http://webix.com/ru/demo/treetable/checkboxes/
try to check first cell - 'Layout branch' then open it. - 'Layout branch' title become '1'
![screenshot_103](https://cloud.githubusercontent.com/assets/5741654/19776686/cccb421e-9c7d-11e6-89d3-2d7ec07d81cf.png)

**Comment by HannaBabrouskaya** [comment]
@Spoonin bug was fixed
