### ISSUE TITLE
Accordion 'animate' prop doesn't take an effect

### ISSUE THREAD

**Issue by Spoonin** [webix-hub/tracker#295]
Accordion - [Animate Property](http://docs.webix.com/api__link__ui.accordion_animate_config.html) seems doesn't take an effect: http://webix.com/snippet/af00bb4a

**Comment by HannaBabrouskaya** [comment]
@Spoonin your issue can be solved with changing css like [here](http://webix.com/snippet/e4b4a544). 
'animate' property is used in a little bit different way. As it is implemented within multiview, so 'animate' can be applied to multiview(and accordion can be part of multiview). 
http://docs.webix.com/desktop__animation.html
