### ISSUE TITLE
'unsafe-eval' is not an allowed source of script

### ISSUE THREAD

**Issue by dutu** [webix-hub/tracker#296]
I'm trying to use webix in a Meteor application deployed on Heroku.
Following error is triggered (and nothing displayed in the browser)

`Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'"`

![](http://i.imgur.com/mfIm15l.jpg)

Note I have renamed : `webix.js` to `_webix.js`

**Comment by PhilAndrew** [comment]
Did you solve this?

**Comment by dutu** [comment]
@PhilAndrew issue is not resolved, but to work around the error I have used
`BrowserPolicy.content.allowEval();` in my Meteor app

**Comment by HannaBabrouskaya** [comment]
You can set "webix.env.strict" to true. This ahould solve the problem with 'unsafe-eval'

**Comment by dutu** [comment]
Thanks!

**Comment by letienan1998** [comment]
> You can set "webix.env.strict" to true. This ahould solve the problem with 'unsafe-eval'

I have the same problem and i have set it in my source code"webix.env.strict" to true (i set it in init function each file are using webix). but nothing happend. Could you please provide another solution for this issue?
