### ISSUE TITLE
Form ValidationSuccess event works confusingly

### ISSUE THREAD

**Issue by Spoonin** [webix-hub/tracker#297]
[Documentation](http://docs.webix.com/api__link__ui.form_onvalidationsuccess_event.html) says: fires after the form has passed validation successfully, but in the [case](http://webix.com/snippet/8505d2ca) it's not working as described

**Comment by HannaBabrouskaya** [comment]
@Spoonin you are right, it fires after every item validation. Documentation text will be changed. 
If you need an event to deal with whole form validation you can use [onAfterValidation](http://docs.webix.com/api__link__ui.form_onaftervalidation_event.html). 
Thank you for pointing it out

**Comment by HannaBabrouskaya** [comment]
Documentation was fixed
