### ISSUE TITLE
Webix 3.2-4.1 bug on mobile with loading subviews using menu on webix jet.

### ISSUE THREAD

**Issue by mzmrk** [webix-hub/tracker#299]
How to reproduce bug:
1. Download: http://webix.com/packages/webix-app-start.zip
2. Upgrade webix codebase to any version above 3.1 up to 4.1
3. Run it on http server.
4. Use mobile browser on iPad 2 or Use any iPad/Google Nexus emulaotr in chrome broswer.
4. after reloading page try touching menu button that will load other subview.
5. $subview will not load properly.

This issue sometimes will randomly popup even after initial load of all $subviews by randomly spam clicking on them all. Confirmed to happend in iPad1 emulator on google chrome with 4 subviews.

**Comment by HannaBabrouskaya** [comment]
@mzmrk fixed and will be available in the next webix version
