### ISSUE TITLE
Datatable/Treetable Colspan over hidden columns

### ISSUE THREAD

**Issue by reynardmc22** [webix-hub/tracker#303]
Displays incorrectly, this is the columns data

{ id:"mbrs", width:55, header:[ {text:"Eligible Charge", colspan:4}, "Mbrs" ] },
{ id:"pctMbrs", header:["", "% Mbrs"], width:75},
{ id:"incidents", header:["", "Services"], width:70, hidden:true},
{ id:"pctIncid", header:["", "% Services"], width:85, hidden:true},
{ id:"eligCharge", header:["", "Elig Charge"], width:90},
{ id:"pctEligCharge", header:["", "% Elig Charge"], width:90}

**Comment by mkozhukh** [comment]
Hi,

It is expected, the initially defined colspan includes all columns from initial config, including the hidden one. ( components, renders self with colspan, and hides necessary columns after that ) 

Just increase the colspan to include hidden columns as well http://webix.com/snippet/e68f5ed2
