### ISSUE TITLE
Backward navigation of Datatable with dynamic data is broken

### ISSUE THREAD

**Issue by k8n** [webix-hub/tracker#309]
Bug demo snippet: https://webix.com/snippet/3863d95a

Probably related, navigation using keyboard arrows may also result in excessive server request pattern as well.

See line 19826 of webix_debug.js (4.3.8).

In my case, users navigate the datatable backwards. I.e. the tail end of the data is loaded first, and users may use keyboard to scroll backwards. Webix confuses direction of scrolling due to the strategy used on line 19826, which results in a server request being issued for each up arrow key press (webix preloads data in the wrong direction).

**Comment by mkozhukh** [comment]
Thanks for reporting the issue.
The fix will be included in Webix 5.1
