### ISSUE TITLE
undoOnError functionality is misleading, doc unclear

### ISSUE THREAD

**Issue by k8n** [webix-hub/tracker#311]
When [```undoOnError```](https://docs.webix.com/api__dataprocessor_undoonerror_config.html) of DataProcessor is set to true, undo history for the particular item is removed when it is saved.

Perhaps this option would be better off renamed to ```clearUndoHistoryOnSave```.  :-)

Excerpt from webix_debug.js:
```
                //clean undo history, for the saved record
		if(this._settings.undoOnError && master._settings.undo)
			master.removeUndo(newid||id);
```

**Comment by HannaBabrouskaya** [comment]
@k8 you are right if there is no error on item save then the undo history is cleared. And if there is an error then master.undo will be called. 
As it is said in the documentation undoOnError "defines whether undo will be made if server returns error response" so the method name will stay + we wll add an information about clearing.
